# Generated by Django 5.2.7 on 2025-10-20 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordering_app", "0002_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productattribute",
            options={
                "verbose_name": "Product Attribute",
                "verbose_name_plural": "Product Attributes",
            },
        ),
        migrations.AlterModelOptions(
            name="productattributevalue",
            options={
                "verbose_name": "Product Attribute Value",
                "verbose_name_plural": "Product Attribute Values",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Supplier", "verbose_name_plural": "Suppliers"},
        ),
        migrations.AlterField(
            model_name="category",
            name="external_id",
            field=models.IntegerField(unique=True, verbose_name="External ID"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="ordering_app.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Product Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SKU"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Stock Quantity"),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="ordering_app.supplier",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Attribute Name"
            ),
        ),
        migrations.AlterField(
            model_name="productattributevalue",
            name="value",
            field=models.CharField(max_length=255, verbose_name="Value"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Contact Person"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Supplier Name"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Phone"
            ),
        ),
    ]
